// pizza
export const GET_PIZZAS_REQUEST = "GET_PIZZAS_REQUEST";
export const GET_PIZZAS_SUCCESS = "GET_PIZZAS_SUCCESS";
export const GET_PIZZAS_FAILED = "GET_PIZZAS_FAILED";

// addPizza
export const ADD_PIZZAS_REQUEST = "ADD_PIZZAS_REQUEST";
export const ADD_PIZZAS_SUCCESS = "ADD_PIZZAS_SUCCESS";
export const ADD_PIZZAS_FAILED = "ADD_PIZZAS_FAILED";

// get One pizza
export const GET_PIZZABYID_REQUEST = "GET_PIZZABYID_REQUEST";
export const GET_PIZZABYID_SUCCESS = "GET_PIZZABYID_SUCCESS";
export const GET_PIZZABYID_FAILED = "GET_PIZZABYID_FAILED";

//update Pizza
export const UPDATE_PIZZA_REQUEST = "UPDATE_PIZZA_REQUEST";
export const UPDATE_PIZZA_SUCCESS = "UPDATE_PIZZA_SUCCESS";
export const UPDATE_PIZZA_FAILED = "UPDATE_PIZZA_FAILED";

//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

// user
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";

// user Login
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";

//Order
export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";

// getUserOrders
export const GET_ORDERS_REQUEST = "PLACE_ORDER_REQUEST";
export const GET_ORDERS_SUCCESS = "PLACE_ORDER_SUCCESS";
export const GET_ORDERS_FAILED = "PLACE_ORDER_FAILED";
